<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Girvs\Girvs.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.MySql" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.Kafka" Version="13.4.6"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Girvs.Aspire.Hosting.Tests"/>
    </ItemGroup>
</Project>
