<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Girvs\Girvs.csproj" />
    <!-- 根模块 [DependsOn] 声明需要引用对应组件模块类型 -->
    <ProjectReference Include="..\..\Girvs.Cache\Girvs.Cache.csproj" />
    <ProjectReference Include="..\..\Girvs.EntityFrameworkCore\Girvs.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\Girvs.EventBus\Girvs.EventBus.csproj" />
  </ItemGroup>
</Project>
