// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SmartProducts.Person.Infrastructure.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    partial class PersonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartProducts.Person.Core.Entities.PersonInfoEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ConstructionUnitId")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CurrentInAreaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Education")
                        .HasColumnType("int");

                    b.Property<int>("HeadPortraitId")
                        .HasColumnType("int");

                    b.Property<string>("IDNo")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("MedicalHistory")
                        .HasColumnType("bit");

                    b.Property<string>("Mobilephone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PoliticOutlook")
                        .HasColumnType("int");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkCard")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("WorkType")
                        .HasColumnType("int");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("IP_PersonInfo");
                });

            modelBuilder.Entity("SmartProducts.Person.Core.Entities.PersonnelQualificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CertificateDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateNO")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CertificateName")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CertificatePic")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("PersonId")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("PersonInfoId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonInfoId");

                    b.ToTable("IP_PersonnelQualification");
                });

            modelBuilder.Entity("SmartProducts.Person.Core.Entities.PersonnelQualificationEntity", b =>
                {
                    b.HasOne("SmartProducts.Person.Core.Entities.PersonInfoEntity", "PersonInfo")
                        .WithMany("PersonnelQualifications")
                        .HasForeignKey("PersonInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
